Repository involveMINT/iMPublic, pull requests merged in 2023-04, with the labels that each got.

#49 Added hi/fi comments UI and relevant functionalities
  libs/client/shared/data-access/src/lib/+state/comments/comments.reducer.ts
  libs/client/shared/data-access/src/lib/+state/comments/comments.selectors.ts
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.ts
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.html
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.scss
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.ts
  libs/server/core/application-services/src/lib/comment/comment.service.ts
  libs/server/core/domain-services/src/lib/comment/comment.entity.ts
  libs/shared/domain/src/lib/domain/comment/comment.dtos.ts
  libs/shared/domain/src/lib/domain/comment/comment.model.ts
  libs/shared/domain/src/lib/domain/comment/comment.queries.ts
  package-lock.json
  package.json
Labels: enhancement

#72 Add Functional Infinite Scroll to ActivityPost Feed
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.actions.spec.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.actions.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.effects.spec.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.effects.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.reducer.spec.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.reducer.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.selectors.ts
  libs/client/shared/data-access/src/lib/+state/user.facade.ts
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.html
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.ts
  libs/server/core/application-services/src/lib/activity-post/activity-post.service.ts
  libs/shared/domain/src/lib/domain/activity-post/activity-post.orchestration.ts
  libs/shared/domain/src/lib/domain/activity-post/activity-post.queries.ts
  libs/shared/domain/src/lib/domain/user/user.queries.ts
Labels: enhancement

#75 Add ActivityPost Code Documentation
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.actions.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.effects.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.reducer.ts
  libs/client/shared/data-access/src/lib/+state/activity-posts/activity-posts.selectors.ts
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.ts
  libs/client/shell/src/lib/activityfeed/activityposts/modal-digest/modal-digest.component.ts
  libs/client/shell/src/lib/activityfeed/activityposts/modal-post/modal-post.component.ts
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.ts
  libs/server/core/application-services/src/lib/activity-post/activity-post.service.ts
  libs/server/core/domain-services/src/lib/activity-post/activity-post.entity.ts
  libs/server/core/domain-services/src/lib/activity-post/activity-post.repository.ts
  libs/server/orcha/src/lib/activity-post/activity-post.orchestration.ts
  libs/shared/domain/src/lib/domain/activity-post/activity-post.dtos.ts
  libs/shared/domain/src/lib/domain/activity-post/activity-post.model.ts
  libs/shared/domain/src/lib/domain/activity-post/activity-post.orchestration.ts
  libs/shared/domain/src/lib/domain/activity-post/activity-post.queries.ts
Labels: documentation

#79 Fix same comments appearing for all posts
  libs/client/shared/data-access/src/lib/+state/comments/comments.reducer.ts
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.ts
Labels: bug

#84 Fix 'loadMore' Event Stuck @ 1-Page-Only Situation
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.ts
Labels: bug

#93 Add UI Fixes from Dan Feedback
  libs/client/shell/src/lib/activityfeed/activityposts/modal-digest/modal-digest.component.html
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.html
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.scss
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.ts
Labels: bug

#97 Make admin moderation hifi + enable toggling between all/flagged posts
  libs/client/admin/shell/src/lib/moderation/comments/modal-comments.component.scss
  libs/client/admin/shell/src/lib/moderation/moderation.component.html
  libs/client/admin/shell/src/lib/moderation/moderation.component.scss
  libs/client/admin/shell/src/lib/moderation/moderation.component.ts
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.html
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.scss
  libs/client/shell/src/lib/activityfeed/activityposts/activityposts.component.ts
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.scss
  libs/client/shell/src/lib/im-app/im-app.component.ts
Labels: feature

#105 fixed the double icon issue
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.html
Labels: bug, S T-Shirt

#106 Enhancement/admin panel migration
  libs/client/admin/shell/src/lib/moderation/moderation.component.html
  libs/client/admin/shell/src/lib/moderation/moderation.component.scss
  libs/client/admin/shell/src/lib/moderation/moderation.component.ts
Labels: feature, M T-Shirt, Should Have

#110 Added requested hifi comments changes
  libs/client/shared/scss/src/lib/_vars.scss
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.html
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.scss
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.ts
Labels: bug, enhancement

#111 Update admin page to match latest activity feed UI
  libs/client/admin/shell/src/lib/moderation/moderation.component.html
  libs/client/admin/shell/src/lib/moderation/moderation.component.scss
Labels: enhancement, S T-Shirt, Should Have

#115 final frontend touches
  libs/client/admin/shell/src/lib/moderation/moderation.component.html
  libs/client/admin/shell/src/lib/moderation/moderation.component.scss
  libs/client/shell/src/lib/activityfeed/activityposts/comments/modal-comments.component.scss
  libs/client/shell/src/lib/activityfeed/activityposts/post/post.component.scss
Labels: enhancement, XS T-Shirt
